export const popularCars = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2024,
    type: "Sedan",
    fuel: "Gasoline",
    price: 27900,
    horsepower: 203,
    mpg: { city: 28, highway: 39 },
  },
  {
    id: 2,
    make: "Honda",
    model: "CR-V",
    year: 2024,
    type: "SUV",
    fuel: "Gasoline",
    price: 31900,
    horsepower: 190,
    mpg: { city: 28, highway: 34 },
  },
  {
    id: 3,
    make: "Tesla",
    model: "Model 3",
    year: 2025,
    type: "Sedan",
    fuel: "Electric",
    price: 38990,
    horsepower: 271,
    range: 272,
  },
  {
    id: 4,
    make: "Ford",
    model: "F-150",
    year: 2024,
    type: "Truck",
    fuel: "Gasoline",
    price: 36995,
    horsepower: 290,
    mpg: { city: 20, highway: 26 },
  },
  {
    id: 5,
    make: "Hyundai",
    model: "Ioniq 5",
    year: 2025,
    type: "SUV",
    fuel: "Electric",
    price: 43700,
    horsepower: 225,
    range: 303, // miles
  },
  {
    id: 6,
    make: "Mazda",
    model: "CX-5",
    year: 2024,
    type: "SUV",
    fuel: "Gasoline",
    price: 29900,
    horsepower: 187,
    mpg: { city: 24, highway: 30 },
  },
  {
    id: 7,
    make: "Chevrolet",
    model: "Silverado 1500",
    year: 2024,
    type: "Truck",
    fuel: "Gasoline",
    price: 40900,
    horsepower: 310,
    mpg: { city: 19, highway: 22 },
  },
  {
    id: 8,
    make: "Rivian",
    model: "R1T",
    year: 2025,
    type: "Truck",
    fuel: "Electric",
    price: 73900,
    horsepower: 600,
    range: 328,
  },
  {
    id: 9,
    make: "Toyota",
    model: "RAV4",
    year: 2024,
    type: "SUV",
    fuel: "Gasoline",
    price: 29975,
    horsepower: 203,
    mpg: { city: 27, highway: 35 },
  },
  {
    id: 10,
    make: "Kia",
    model: "Telluride",
    year: 2024,
    type: "SUV",
    fuel: "Gasoline",
    price: 36890,
    horsepower: 291,
    mpg: { city: 20, highway: 26 },
  },
];
